parameters:
#    b55_yarg_api.example.class: B55\Bundle\YargAPIBundle\Example

services:
#    b55_yarg_api.example:
#        class: %b55_yarg_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
