#cvs:
#    type:     rest
#    resource: B55\Bundle\YargBundle\Controller\ApiController
#    prefix: /api/v1/

yarg_index:
    pattern: /
    defaults: { _controller: B55YargBundle:Index:index }
    requirements:
        method: GET

yarg_myyarg:
    pattern: /my-yarg
    defaults: { _controller: B55YargBundle:MyYarg:Index }
    requirements:
        method: GET

yarg_myyarg_new_cv:
    pattern: /my-yarg/add/cv
    defaults: { _controller: B55YargBundle:MyYarg:addCv }

yarg_list_cv:
    pattern: /my-cvs
    defaults: { _controller: B55YargBundle:Index:list }
    requirements:
        method: GET
