#cvs:
#    type:     rest
#    resource: B55\Bundle\YargBundle\Controller\ApiController
#    prefix: /api/v1/

yarg_myyarg:
    pattern: /my-yarg
    defaults: { _controller: B55YargBundle:MyYarg:Index }
    requirements:
        method: GET


# Information
yarg_myyarg_add_category_info:
    pattern: /my-yarg/cv/{slug}/category/{category_id}/add/info
    defaults: { _controller: B55YargBundle:Informations:addToCategory }
    requirements:
        category_id: \d+

yarg_myyarg_edit_category_info:
    pattern: /my-yarg/cv/{slug}/category/{category_id}/info/{info_id}/edit
    defaults: { _controller: B55YargBundle:Informations:edit }
    requirements:
        info_id: \d+
        category_id: \d+

yarg_myyarg_del_category_info:
    pattern: /my-yarg/cv/{slug}/category/{category_id}/info/{info_id}/delete
    defaults: { _controller: B55YargBundle:Informations:delete }
    requirements:
        category_id: \d+
        info_id: \d+


# Cv Information
yarg_myyarg_add_cv_info:
    pattern: /my-yarg/cv/{slug}/info/add
    defaults: { _controller: B55YargBundle:Informations:addToCv }

yarg_myyarg_edit_cv_info:
    pattern: /my-yarg/cv/{slug}/info/{info_id}/edit
    defaults: { _controller: B55YargBundle:Informations:edit }
    requirements:
        info_id: \d+

yarg_myyarg_del_cv_info:
    pattern: /my-yarg/cv/{slug}/info/{info_id}/delete
    defaults: { _controller: B55YargBundle:Informations:delete }


# Category
yarg_myyarg_add_category:
    pattern: /my-yarg/cv/{slug}/category/add/{parent}
    defaults: { _controller: B55YargBundle:Categories:add, parent: null }
    requirements:
        parent: \d+

yarg_myyarg_del_category:
    pattern: /my-yarg/cv/{slug}/category/{category_id}/delete
    defaults: { _controller: B55YargBundle:Categories:delete }
    requirements:
        category_id: \d+

yarg_myyarg_edit_category:
    pattern: /my-yarg/cv/{slug}/category/{category_id}/edit
    defaults: { _controller: B55YargBundle:Categories:edit }
    requirements:
        category_id: \d+


# CV
yarg_myyarg_new_cv:
    pattern: /my-yarg/add/cv
    defaults: { _controller: B55YargBundle:Cvs:add }

yarg_myyarg_show_cv:
    pattern: /my-yarg/cv/{slug}
    defaults: { _controller: B55YargBundle:Cvs:show }

yarg_myyarg_delete_cv:
    pattern: /my-yarg/cv/{slug}/delete
    defaults: { _controller: B55YargBundle:Cvs:delete }

yarg_myyarg_edit_cv:
    pattern: /my-yarg/cv/{slug}/edit
    defaults: { _controller: B55YargBundle:Cvs:edit }


# Public CV URL
yarg_show_public_cv:
    pattern: /cv/{user_slug}/{cv_slug}
    defaults: { _controller: B55YargBundle:Cvs:showPublic }

