parameters:
#    b55_yarg.example.class: B55\Bundle\YargBundle\Example

services:
#    b55_yarg.example:
#        class: %b55_yarg.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
