root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

yarg:
    resource: "@B55YargBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: en

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

b55_yarg_web_site:
    resource: "@B55YargWebSiteBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: en

b55_yarg_admin:
    resource: "@B55YargAdminBundle/Resources/config/routing.yml"

b55_yarg_api:
    resource: "@B55YargAPIBundle/Resources/config/routing.yml"

