security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        yarg_api:
            pattern: ^/api
            security: false
#            http_basic:
#                provider: fos_userbundle
#                realm: "Secured API"
#            logout: false
#            anonymous: false

        yarg_ui:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            form_login:
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                always_use_default_target_path: true
                default_target_path: yarg_myyarg
                target_path_parameter: _target_path
                use_referer: false
            logout:
                path: fos_user_security_logout
                target: yarg_index

    access_control:
        - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/[a-z]+/my-yarg, role: ROLE_USER }
        - { path: ^/[a-z]+/yarg/admin/, role: ROLE_ADMIN }

