<?php

namespace B55\Bundle\YargBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRepository extends EntityRepository
{
  public function getLastPublishedCvs()
  {
      $query = $this->createQueryBuilder('c')
        ->select('c')
        ->from('B55YargBundle:Cv', 'cv')
        ->where('cv.published = 1')
        ->orderBy('cv.id', 'DESC')
        ->setMaxResults(5)
        ->getQuery();

      return $query->getResult();
  }
}
