parameters:
#    b55_yarg_web_site.example.class: B55\Bundle\YargWebSiteBundle\Example

services:
#    b55_yarg_web_site.example:
#        class: %b55_yarg_web_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
